version: '3.8'

services:
  basecleanarchitecture.api:
    environment:
      - AppConnection=Server=db;Database=BaseCleanArchitecture;User=sa;Password=Passw0rd!
    image: ${DOCKER_REGISTRY-}basecleanarchitecture
    build:
      context: .
      dockerfile: src/BaseCleanArchitecture.API/Dockerfile
    ports:
      - "80:5000"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - SA_PASSWORD=Passw0rd!
        - ACCEPT_EULA=Y
    ports:
      - "1401:1433"
